config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :pubs, only: %i[index new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pub.rb
class Pub < ApplicationRecord
  DISTRICTS = [
    "Alna",
    "Bjerke",
    "Frogner",
    "Gamle Oslo",
    "Grorud",
    "Grünerløkka",
    "Nordre Aker",
    "Nordstrand",
    "Sagene",
    "St. Hanshaugen",
    "Stovner",
    "Søndre Nordstrand",
    "Ullern",
    "Vestre Aker",
    "Østensjø"
  ]

  validates :name, presence: true, uniqueness: true
  validates :address, :description, :photo, presence: true
  validates :district, presence: true, inclusion: { in: DISTRICTS }

  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_action :authenticate_user!

  layout :layout_by_resource

  private

  def layout_by_resource
    if devise_controller? && action_name != "edit"
      "authentication"
    else
      "application"
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @pubs = Pub.all
  end
end

app/controllers/pubs_controller.rb
class PubsController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @pubs = Pub.where.not(latitude: nil, longitude: nil)

    @markers = @pubs.map do |pub|
      {
        lat: pub.latitude,
        lng: pub.longitude,
        infoWindow: render_to_string(partial: "infowindow", locals: { pub: pub })
      }
    end
  end

  def new
    @pub = Pub.new
  end

  def create
    @pub = Pub.new(pub_params)

    if @pub.save
      redirect_to pubs_path
    else
      render :new
    end
  end

  private

  def pub_params
    params.require(:pub).permit(:name, :address, :district, :description, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pubcrawler</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <div class="page-wrapper">
      <%= yield %>
    </div>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/layouts/authentication.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Pubcrawler</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body class="authentication-body">
    <div class="signup-wrapper">
      <%= yield %>
    </div>
    <%= javascript_include_tag 'application' %>
</body>
</html>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<div class="container">
  <section id="section-one">
    <h4>OSLO</h4>
    <div class="row">
      <% @pubs.each do |pub| %>
        <div class="col-xs-12 col-sm-4">
          <%= render pub %>
        </div>
      <% end %>
    </div>
  </section>
</div>

app/views/pubs/_form.html.erb
<%= simple_form_for(@pub) do |f| %>
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :district, collection: Pub::DISTRICTS %>
    <%= f.input :description %>
    <%= f.input :photo %>
  </div>

  <%= f.button :submit, class: "btn btn-base btn-brand" %>
<% end %>

app/views/pubs/_infowindow.html.erb
<div style="color: black;">
  <h2><%= pub.name %></h2>
  <p><%= pub.address %></p>
</div>

app/views/pubs/_pub.html.erb
<div id="pub-<%= pub.id %>" class="pub card-row">
  <div class="card">
    <div class="wrapper" style="background: linear-gradient(to bottom,rgba(20,20,20, 0.8),rgba(76,76,76,0.2) 30%), url(<%= pub.photo || "https://tvseriescritic.files.wordpress.com/2016/10/stranger-things-bicycle-lights-children.jpg" %>) center / cover no-repeat;">
      <div class="header">
        <div class="date">
          <span class="day"><%= pub.created_at.strftime("%d") %></span>
          <span class="month"><%= pub.created_at.strftime("%b") %></span>
          <span class="year"><%= pub.created_at.strftime("%Y") %></span>
        </div>
          <ul class="menu-content">
            <li>
              <a href="#">
                <%= icon("far", "bookmark") %>
              </a>
            </li>
            <li>
              <%= icon("fas", "heart") %>
            </li>
            <li>
              <a href="#">
                <%= icon("far", "comment") %>
              </a>
            </li>
          </ul>
      </div>
      <div class="data">
        <div class="content">
          <span class="author"><%= pub.district %></span>
          <h1 class="title"><a href="#"><%= pub.name %></a></h1>
          <p class="text"><%= pub.description.truncate(105) if pub.description %></p>
          <%= link_to "See more", "#", class: "button", remote: true %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pubs/index.html.erb
<div class="main-container">
  <div class="results-container">
    <%= render @pubs %>
  </div>

  <div
    id="map"
    class="search-map"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>
</div>

app/views/pubs/new.html.erb
<div class="container" style="margin-top: 70px">
  <h1>New Pub</h1>

  <%= render 'form', pub: @pub %>

  <%= link_to 'Back', pubs_path %>
</div>

app/views/shared/_banner.html.erb
<div class="banner">
  <div class="banner-content">
    <h1 id="banner-text">pubcrawler</h1>
    <p>Discover the best cocktail bars in Oslo</p>
    <ul class="slideshow">
      <li></li>
      <li></li>
      <li></li>
      <li></li>
    </ul>
  </div>
</div>
<%= icon("fas", "chevron-down") %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><%= icon("fab", "github") %></a>
    <a href="#"><%= icon("fab", "instagram") %></a>
    <a href="#"><%= icon("fab", "facebook") %></a>
    <a href="#"><%= icon("fab", "twitter") %></a>
    <a href="#"><%= icon("fab", "linkedin") %></a>
  </div>
  <div class="footer-copyright">
    This footer is made with 🍺 at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon navbar-wagon-fixed">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png", height: 50 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Links -->
    <%= link_to "Pubs", pubs_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <%= link_to "New Pub", new_pub_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <!-- Avatar with dropdown menu -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/arthur-littm", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-cog"></i>  <%= t(".settings", default: "Settings") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>